### PR TITLE
Persian Translate !!

### PR DESCRIPTION
**Pull request by Punsher2011**
Hello,
Because Persian is RTL language and some control string and other stuff are LTR this might need some changes .
please inform me of the problem that might exist and i'll change them.
thanks

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
@Punsher2011 awesome!

I'll prepare build of WAIL Beta for you and give it to you so you'll be able to check it's behavior and make fixes if they will be required

Thank you

**Comment by Punsher2011** [comment]
Wow awesome.
Many thanks to you .

**Comment by artem-zinnatullin** [comment]
Here is build 1: https://drive.google.com/file/d/0B542XgUF004OcVd0MnBIbmtkLUU/view?usp=sharing

Waiting for your comments

**Comment by Punsher2011** [comment]
Hello my Droid Razr doesn't support persian how ironic LOL and changing language lead to crash :D
1- IF changing lang could have be done before authentication process it would have been better .

Anyhow i test it and made some change to strings to so it could be better .

2- This picture i included are the way the app currently are and how it should be .
in the top of the picture before separating line is the current format and below is how it should be .

it think some problem is because line are centered without direction being changed LOOL ( novice idea he he )

Thanks

**Comment by regisd** [comment]
Also all toggle buttons should be at the end (left) rather than stat (right)

**Comment by regisd** [comment]
Well, I created #182 to track the implementation of RTL, independently of Persian.

**Pull request closed without merging**
