### PR TITLE
Option to ignore any player

### LINKED ISSUE #76: Add option to ignore some media players
As proposed in #63, it might be not desired to scrobble tracks from some players.

### PR DESCRIPTION
**Pull request by ilya-murzinov**
TODO:
 - ~~There should be application label instead of package name displayed on main screen~~
 - ~~When player removed from ignored, scrobbling should immediately start (if it's possible)~~
 - ~~German translation~~ (will be done after merging)
 - ...

resolves #76

### CODE REVIEW

**Comment by ilya-murzinov** [comment]
Not finished, it's just easier to track todo-list here :)

**Comment by ilya-murzinov** [comment]
@tehabe, can you us help with German translation again?

**Comment by tehabe** [comment]
Yes. Will check it out later today.

**Comment by ilya-murzinov** [comment]
@tehabe, thank you!
I will test this PR further tomorrow and hopefully merge it, you can start immediately after that.

**Comment by tehabe** [comment]
@ilya-murzinov @artem-zinnatullin Did you fix the "scrobble over cell network" so that the positive question makes sense?

Also, that the select language is not translatable is weird, only the list itself shouldn't be translated I think.

**Comment by ilya-murzinov** [comment]
@tehabe, yes I fixed "scrobble over cell network"
@artem-zinnatullin what do you this about translating "select language" settings item? Why did you make it not translatable?

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov I marked "Select language" as not translatable because if wrong language will be selected (by the user or automatically) it would be very hard to find "Select language" option in unknown language, so may be it's okay to always display it in English

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin, yeah, I thought so :)
So we are keeping it that way?

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov I think it's okay to leave it in English

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin, alright

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin, BTW, can you also review (may be test) this PR? :)

**Comment by artem-zinnatullin** [comment]
Okay, in progress...

**Comment by artem-zinnatullin** [comment]
Awesome, tested with Poweramp, Google Play Music, Pocket Casts!

Now I'll review the code

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov LGTM, good work, users will be happy :)

**Comment by ilya-murzinov** [comment]
Alright then, merging!
@tehabe you can start translating now. BTW, I've translated some string myself previously (well, using Google Translate, shame on me), can you please check the whole translation?

**Pull request merged**
