### PR TITLE
Update build tools

### PR DESCRIPTION
**Pull request by regisd**
- Update Gradle to 2.4
- Update target SDK to 22
- Update build tools to 22.0.1

### CODE REVIEW

**Comment by ilya-murzinov** [comment]
@regisd, please also update build-tools version in our [TravisCI script](https://github.com/artem-zinnatullin/android-wail-app/blob/develop/.travis.yml#L5). I'm afraid that build will fail otherwise.

**Comment by ilya-murzinov** [comment]
Yep, and, apparently, [Android version](https://github.com/artem-zinnatullin/android-wail-app/blob/develop/.travis.yml#L6) too :)

**Comment by regisd** [comment]
Travis-CI conf updated. Sorry, I don't have much experience with Travis.
I'm not even sure they have deployed the latest versions on their servers.

**Comment by regisd** [comment]
Let's wait for the Travis presubmit check to see the outcome.

**Comment by ilya-murzinov** [comment]
Yes, build can take a long time when Travis is busy, but we'll wee :)

**Comment by regisd** [comment]
It seems to fetch everything, and even accept the license :-)

**Comment by ilya-murzinov** [comment]
Yes, it's OK!
Merging this, thanks again, @regisd! :)

**Pull request merged**
