### PR TITLE
German Translation updated

### PR DESCRIPTION
**Pull request by tehabe**
I added the strings I found and updated already existing strings.

### CODE REVIEW

**Comment by ilya-murzinov** [comment]
@tehabe, build is failing, problem with settings_ignored_players_item_title:

>* What went wrong:
>Execution failed for task ':wail-app:mergeReleaseResources'.
> > /home/travis/build/artem-zinnatullin/android-wail-app/wail-app/src/main/res/values-de/strings.xml: Error: Found item String/settings_ignored_players_item_title more than one time

**Comment by tehabe** [comment]
More than one time? It only once in the file.

**Comment by ilya-murzinov** [comment]
Hm, really strange. It builds normally on my PC.

**Comment by ilya-murzinov** [comment]
@tehabe thank you very much for your help!

**Comment by ilya-murzinov** [comment]
It's ok now.

**Pull request merged**
