### PR TITLE
Logout

### LINKED ISSUE #85: Add option to logout
We don't currently have any way to log out, except uninstalling the app.
There must be new settings item which allow user to log out.

### PR DESCRIPTION
**Pull request by ilya-murzinov**
resolves #85

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov LGTM :+1: , btw check [Material-Dialogs](https://github.com/afollestad/material-dialogs) library, it's pretty good, I use it in one app, may be you'll switch all dialogs on it?

And one more thing: Kotlin, I'm already using it, my opinion — it's very good, so I can help with integrating it in project if you'd like to use new awesome language :)

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin, nice library, it will be really easy to use it instead of standard Android one.

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin, I don't know a lot about Kotlin and haven't ever used it. But if we decide to use it, we gonna rewrite everything from scratch :)

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov no! We can simply rewrite class by class in Kotlin, Kotlin -> Java and Java -> Kotlin works without problems :+1: 

I can help in the beginning :)

**Pull request merged**
