### PR TITLE
New navigation drawer

### LINKED ISSUE #95: New nav. drawer
Thanks to [this](https://play.google.com/store/apps/details?id=com.artemzin.android.wail&reviewId=Z3A6QU9xcFRPR2Nab3ljdnBOZ2VyTFhUMW1namdFazNocGFyR1FRWXlJQm9sWmtGSzdUYkx3SE5hTmpQX0hUYzlOWkZEb2tRaVVyNG9WVG9yN2kxWHFPcnc) review on Google Play.

>Последнее обновление вообще шикарно, но гайдлайны автору все же лучше перечитать :) Иконка поиска и боковое меню не вписываются.

Guidelines: [navigation drawer](http://www.google.com/design/spec/patterns/navigation-drawer.html)

### PR DESCRIPTION
**Pull request by ilya-murzinov**
TODO:
 - ~~Username and date of registration are empty when user gets logged in first time~~

resolves #95

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov let me check this before merging

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin sure

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov sorry for the delay

LGTM, but on Nexus 7 Navigation Drawer has too big width

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin, hmmm according to guidelines, drawer width should be **(screen width - action bar height)**. I forgot that I hardcoded 56dp instead of action bar height, but it wont change a lot.
How do you think, what width should we use?

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin, nevermind, I found what I needed.

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov :)

On Sat, Jan 24, 2015 at 8:21 PM, Ilya Murzinov <notifications@github.com>
wrote:

> @artem-zinnatullin <https://github.com/artem-zinnatullin>, nevermind, I
> found what I needed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/artem-zinnatullin/android-wail-app/pull/99#issuecomment-71327891>
> .
>



-- 
------------------
Best regards, Artem Zinnatullin
Sent from my bed.

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin I'm not quite sure that I did it right.

It's written in guidelines:
>The width of the side nav is equal to the width of the screen minus the height of the action bar, or in this case 56dp from the right edge of the screen. The maximum width of the nav drawer is 5 times the standard increment (56dp on mobile and 64dp on tablet).

But GMail and Play Market always set drawer width to **(display width - action bar height)** in landscape mode. How do they look on tablet?

**Comment by artem-zinnatullin** [comment]
https://medium.com/sebs-top-tips/material-navigation-drawer-sizing-558aea1ad266

сб, 24 янв. 2015, 21:14, Ilya Murzinov <notifications@github.com>:

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin, can you please check again?

**Comment by artem-zinnatullin** [comment]
I am currently at muscle car show :D

сб, 24 янв. 2015, 21:49, Ilya Murzinov <notifications@github.com>:

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin, no problem, it can wait :)

**Comment by artem-zinnatullin** [comment]
сб, 24 янв. 2015, 22:02, Ilya Murzinov <notifications@github.com>:

**Comment by ilya-murzinov** [comment]
@artem-zinnatullin any progress on this?

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov just came from work, I need to eat and relax a bit

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov seems legit, merge it :+1:

**Comment by ilya-murzinov** [comment]
Thanks!

**Pull request merged**
