### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### artem-zinnatullin/android-wail-app now has a Chat Room on Gitter

@artem-zinnatullin has just created a chat room. You can visit it here: [https://gitter.im/artem-zinnatullin/android-wail-app](https://gitter.im/artem-zinnatullin/android-wail-app?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/artem-zinnatullin/android-wail-app?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
@ilya-murzinov hey hey! It's okay :D

**Comment by ilya-murzinov** [comment]
I've added it manually to better place :)

**Comment by artem-zinnatullin** [comment]
Oh, cool

**Comment by ilya-murzinov** [comment]
:)

**Pull request closed without merging**
